pose2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('videos/', include('video.urls')),
    path('accounts/', include('allauth.urls')),
]

video/urls.py
from django.urls import path
from . import views

app_name = 'video'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('pose/<int:video_id>', views.pose, name='pose'),
    path("setup/", views.setup, name="setup"),
    path("show_progress/", views.show_progress, name="show_progress"),
    path("pose_estimation/<int:video_id>", views.pose_estimation, name="pose_estimation"),
    path('gallery/', views.gallery, name='gallery'),
    path('delete/', views.delete, name='delete'),
]

video/models.py
from django.db import models
from django.contrib.auth import get_user_model
from cloudinary.models import CloudinaryField
from cloudinary_storage.storage import VideoMediaCloudinaryStorage
from cloudinary_storage.validators import validate_video

from PIL import Image
import numpy as np
import os

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'videos/{0}/{1}'.format(instance.user.id, filename)


class Progress(models.Model):
    """Progress Management Model"""
    now = models.IntegerField("Current progress", default=0)
    total = models.IntegerField("Total number of steps", default=100)

class VideoCloudinary(models.Model):
    video_file = models.FileField(upload_to=user_directory_path, blank=True, storage=VideoMediaCloudinaryStorage(),
                              validators=[validate_video])
    thumbnail = models.ImageField(blank=True, null=True)  # no need to set storage, field will use the default one
    is_estimated = models.BooleanField(default=False)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, default=1)

    def __str__(self):
        return str(self.video_file.name)

video/forms.py
from django import forms
from .models import VideoCloudinary
from cloudinary.forms import CloudinaryFileField
from cloudinary.forms import CloudinaryJsFileField

class VideoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(VideoForm, self).__init__(*args, **kwargs)
        self.fields['video_file'].label = 'Select'
    
    class Meta:
        model = VideoCloudinary
        fields = ['video_file']
        widgets = {
            'video_file': forms.FileInput(attrs={'accept': 'video/*'})
        }

        video_file = CloudinaryJsFileField()

        

video/views.py
import os
import io
import mediapipe as mp
import numpy as np
import cv2
from PIL import Image
import ffmpeg
import json
import time
import base64

from subprocess import check_output
from .utils import has_audio_streams

from .forms import VideoForm
from .models import Progress, VideoCloudinary

from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

from .pose import pose_function
from django.shortcuts import HttpResponse, render, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt

from django.contrib.auth.models import User

import functools
import datetime as dt

import cloudinary

@login_required
def pose(request, video_id):
    try:
        video_obj = VideoCloudinary.objects.get(id=video_id)
        print("video file url: ", video_obj.video_file.url)
        #video_obj = VideoPost.objects.get(id=video_id)
        params = {
            'panel': 'video/video/pose.mp4',
            'video': video_obj,
        }
        return render(request, 'video/pose.html', params)
    except ObjectDoesNotExist:
        return render(request, 'video/404.html')

@csrf_exempt
def home(request):
    """Base page"""
    #obj = VideoPost()
    obj = VideoCloudinary()
    #cloudinary.uploader.upload(request.FILES)
    #context = dict(direct_form = VideoForm())
    form = VideoForm(request.POST or None, request.FILES or None, instance=obj)
    params = {
        'panel': 'video/video/home.mp4',
        'form': form,
    }

    if request.is_ajax():
        if form.is_valid():
            if request.user.is_authenticated:
                video_from_form = form.save()
                print("video_from_form: ", video_from_form)
                uploaded_video = VideoCloudinary.objects.get(video_file=video_from_form)#, user=request.user)
                #uploaded_video = VideoPost.objects.get(video_file=video_from_form)
                video_url = uploaded_video.video_file.url
                print("\nuploaded video URL: ", video_url)
                
                uploaded_video.user = request.user
                uploaded_video.save(update_fields=['user'])
                print("request user: ", request.user)

                #video_name = uploaded_video.video_file.name # Same file #debug mode
                video_root = uploaded_video.video_file.name # root path (MEDIA_URL + user_directory_path() in models)
                video_name = video_root.rsplit("/", 1)[1]

                #cap = cv2.VideoCapture(os.path.join(settings.MEDIA_ROOT, video_name))
                cap = cv2.VideoCapture(video_url)
                w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
                h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
                fps = cap.get(cv2.CAP_PROP_FPS)
                fourcc = cv2.VideoWriter_fourcc(*'avc1')

                now = dt.datetime.now()
                time = now.strftime('%Y%m%d-%H%M%S')

                #thumbnail_name = video_name.rsplit(".", 1)[0] + '_{}'.format(time) + '.png' # debug mode
                thumbnail_name = '{}_{}.jpg'.format(video_name, time)
                #thumbnail_path = os.path.join("thumbnail", thumbnail_name)
                #dst_path = os.path.join(settings.MEDIA_ROOT, thumbnail_name)
                
                ret, image = cap.read()
                if not ret:
                    print("no ret")
                    return HttpResponse("No frame error.")
                
                if ret==True:
                    #print("\nthumbnail path: ", dst_path)
                    rgb_img = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
                    pil_img = Image.fromarray(rgb_img)
                    img = io.BytesIO() # Creating an empty instance (expand on memory)
                    pil_img.save(img,"JPEG") # Save the PIL in the empty instance as jpeg file
                    bytes_img = img.getvalue() # Get its binary source

                    print("user id: ", uploaded_video.user.id)
                    #thumbnail_dest = 'media/thumbnails/{}/{}'.format(uploaded_video.user.id, thumbnail_name)
                    thumbnail_dest = 'media/thumbnails/{}/'.format(uploaded_video.user.id)
                    print("thumbnail dest: ", thumbnail_dest)

                    thumbnail_url = cloudinary.uploader.upload(bytes_img, folder=thumbnail_dest, resource_type='image')['secure_url'] # front end URL
                    display_url = cloudinary.CloudinaryImage(str(thumbnail_url)).build_url()
                    print("generated: ", display_url)
                    #cv2.imwrite(dst_path, image)
                    #thumbnail_img = cloudinary.CloudinaryImage(thumbnail_name)
                    uploaded_video.thumbnail = display_url#thumbnail_url # assign the generated URL after the Upload (not 'secure_url' itself)
                    print("thumbnail URL: ", uploaded_video.thumbnail)

                    
                    #uploaded_video.thumbnail = thumbnail_name
                    uploaded_video.save(update_fields=['thumbnail'])
                    print("Thumbnail saved.")
                
                return JsonResponse({'message': 'OK!'})
            else:
                return JsonResponse({'message': 'You are not logged in!'})        
            
    return render(request, 'video/home.html', params)

@login_required
def gallery(request):
    try:
        all_videos = VideoCloudinary.objects.filter(user=request.user).all().order_by('-id')
        #all_videos = VideoPost.objects.filter(user=request.user).all().order_by('-id')
        params = {
            'all_videos': all_videos,
        }
        return render(request, 'video/gallery.html', params)
    except ObjectDoesNotExist:
        return render(request, 'video/404.html')

def setup(request):
    """Create a progress management instance"""
    progress = Progress.objects.create()
    return HttpResponse(progress.pk)

def show_progress(request):
    """Run the function"""
    if "progress_pk" in request.GET:
        # Process when progress_pk is specified
        progress_pk = request.GET.get("progress_pk")
        progress = get_object_or_404(Progress, pk=progress_pk)
        percent = str(int(progress.now / progress.total * 100)) + "%"
        return render(request, "video/progress_bar.html", {"percent": percent})
    else:
        return HttpResponse("Error")

def make_progress(pk):
    """Proceed with the progress associated with the primary key"""
    progress = get_object_or_404(Progress, pk=pk)
    progress.now += 1
    progress.save()

def set_argument(pk):
    """Fix the argument"""
    return functools.partial(make_progress, pk=pk)

@login_required
def pose_estimation(request, video_id):
    if "progress_pk" in request.GET:
        progress_pk = request.GET.get("progress_pk")
        
        video_obj = VideoCloudinary.objects.get(id=video_id)
        #video_obj = VideoPost.objects.get(id=video_id)
        video_name = video_obj.video_file.name

        input_video = video_obj.video_file.url
        #input_video = os.path.join(settings.MEDIA_ROOT, video_name)
        audio_flag = has_audio_streams(input_video)
        print("\naudio: ", audio_flag)

        now = dt.datetime.now()
        time_now = now.strftime('%Y%m%d-%H%M%S')

        #thumbnail_path = "thumbnail/" + video_name.rsplit(".", 1)[0] + '_{}'.format(time_now) + '.png'
        thumbnail_path = 'media/thumbnails/{}/'.format(video_obj.user.id)
        print("thumbnail path: ", thumbnail_path)

        #dst_path = video_name.rsplit(".", 1)[0] + '_{}'.format(time_now) + '.mp4'
        #output = os.path.join(settings.MEDIA_ROOT, dst_path)
        output = 'media/videos/{}/'.format(video_obj.user.id)
        print("output path: ", output)

        display_url, video_url = pose_function(set_argument(progress_pk), input_video, output, thumbnail_path, audio_flag)

        result_id = None
        
        #estimated_video = VideoPost(video_file=video_file, thumbnail=thumbnail_path, is_estimated=True, user=request.user)
        estimated_video = VideoCloudinary(
            video_file=video_url, 
            thumbnail=display_url, 
            is_estimated=True, 
            user=request.user
        )
        estimated_video.save()
        result_id = estimated_video.id

        #result_video = VideoPost.objects.get(id=result_id)
        result_video = VideoCloudinary.objects.get(id=result_id)
        video_obj.delete()
        
        return render(request, "video/result.html", {'result_video': result_video})
    else:
        return HttpResponse("Error")

@login_required
def delete(request):
    if request.method == 'GET':
        video_id = request.GET['video_id']
        video_obj = VideoCloudinary.objects.filter(user=request.user).get(id=video_id)
        #video_obj = VideoPost.objects.filter(user=request.user).get(id=video_id)
        video_obj.delete()

        return JsonResponse({'video_id': video_id})
    else:
        return JsonResponse({'status': 'cannot delete'})

video/templates/video/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pose App</title>
    <!--materialize-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Google icon font -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- customcss -->
    <link rel="stylesheet" type="text/css" href="{% static 'video/css/base.css' %}">
    <!--favicon-->
    <link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}"/>
    {% block extracss %}{% endblock %}
</head>

<!-- jQuery, Popper.js, Materialize JS -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>
{% block extrajs %}{% endblock %}

<body>
    <!-- header -->
    <nav>
        <div class="nav-wrapper amber darken-1">
          <a href="{% url 'video:home' %}" class="brand-logo">Pose App</a>
          <a href="" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'video:home' %}"><i class="material-icons">home</i></a></li>
            <li><a href="{% url 'video:gallery' %}"><i class="material-icons">collections</i></a></li>

            {% if user.is_authenticated %}
                <li><a href="#">{{ user.username }}</a></li>
                <li><a href="{% url 'account_logout' %}"><i class="material-icons">power_settings_new</i></a></li>
            {% else %}
                <li><a href="#">Welcome, new user.</a></li>
                <li><a href="{% url 'account_login' %}"><i class="material-icons">person</i></a></li>
            {% endif %}
            
          </ul>
        </div>
    </nav>
    
    <ul class="sidenav" id="mobile-demo">
        <li><a href="{% url 'video:home' %}"><i class="material-icons">home</i>HOME</a></li>
        <li><a href="{% url 'video:gallery' %}"><i class="material-icons">collections</i>POSTS</a></li>

        {% if user.is_authenticated %}
            <li><a href="#"><i class="material-icons">person</i>{{ user.username }}</a></li>
            <li><a href="{% url 'account_logout' %}"><i class="material-icons">power_settings_new</i>Log Out</a></li>
        {% else %}
            <li><a href="#"><i class="material-icons">person</i>Welcome, new user.</a></li>
            <li><a href="{% url 'account_login' %}"><i class="material-icons">person</i>Log In</a></li>
        {% endif %}
    </ul>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <!-- footer -->
    <footer class="page-footer footer-copyright amber darken-1">
          <div class="container">
            <a class="grey-text text-lighten-4" href="https://twitter.com/1220castillo">©2021 Eiji Kitajima</a>
          </div>
    </footer>

    <!-- custom js-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('.sidenav');
            var instances = M.Sidenav.init(elems, 'html');
        });
    </script>

    {% block extrascript %}
    {% endblock %}
</body>
</html>

video/templates/video/gallery.html
{% extends 'video/base.html' %}
{% load static %}
{% load materializecss %}
{% load cloudinary %}

{% block extracss %}
    <!-- customcss -->
    <link rel="stylesheet" type="text/css" href="{% static 'video/css/gallery.css' %}">
{% endblock %}

{% block content %}
    <hr class="blank" color="gray">

    <div id="overlay">
        <div id="spinner-box" class="cv-spinner text-center mt-3">
            <div class="spinner-border text-dark" role="status"></div>
        </div>
    </div>

    <div id="data-box" class="photogallery">
        {% for video in all_videos %}
            <div class="photo">

                <div class="inner">
                    <a href="{% url 'video:pose' video.id %}">
                        <figure class="thumbnail">
                            {% if video.thumbnail %}
                                <img src="{{ video.thumbnail.name}}">
                                <!--<img src="{% static video.thumbnail.url %}">-->
                                <!--<figcaption class="overlay">{{ video.video_file.name }}</figcaption>-->
                            {% endif %}

                            {% if video.is_estimated %}
                                <span class="label material-icons">
                                    circle
                                </span>
                            {% endif %}
                        </figure>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

{% block extrascript %}
    <script>
        $(document).ajaxSend(function(){
            $("#overlay").fadeIn(300);
        });

        $.ajax({
            type: 'GET',
            url: "{% url 'video:gallery' %}",
            success: function(response){
                setTimeout(function(){
                    $("#overlay").fadeOut(300);
                }, 300);
            },
            error: function(error){
                spinnerBox.classList.add('not-visible')
                dataBox.innerHTML = `<b>Failed to load the posts.</b>`
            }
        });
    </script>
{% endblock %}

video/templates/video/home.html
{% extends 'video/base.html' %}
{% load static %}
{% load materializecss %}

{% block extracss %}
    <!-- customcss -->
    <link rel="stylesheet" type="text/css" href="{% static 'video/css/home.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div id="alert-box"></div>

        {% if user.is_authenticated %}
            <form id="upload-form" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|materializecss }}
            </form>
        {% else %}
            <button class="btn yellow darken-2"><a href="{% url 'account_login' %}">Sign Up</a></button>
        {% endif %}
        

        <div id="progress-box" class="not-visible">progress</div>

        <section class="hero">
            <div id="video-box" class="video-box overlay text-center">
                <video class="video" muted autoplay loop playsinline type="video/mp4">
                    <source src="{% static panel %}" poster="{% static 'video/img/home.png' %}">
                </video>
                <div class="log js-log-mp4"></div>
            </div>

            <div id="cancel-box" class="not-visible">
                <button id="cancel-btn" class="btn red lighten-1">cancel</button>
            </div>

            <div id="upload-box" class="not-visible">
                <button type="sumbit" id="upload-btn" class="btn yellow darken-2">upload</button>
            </div>

            <div id="check-box" class="not-visible">
                <button id="check-btn" class="btn green lighten-2" onclick="location.href='{% url 'video:gallery' %}'">check</button>
            </div>

        </section>
        
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

    <!-- custom js-->
    <script type="text/javascript" src="{% static 'video/js/upload.js' %}"></script>
{% endblock %}

video/templates/video/pose.html
{% extends 'video/base.html' %}
{% load static %}

{% block extrajs %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- videojs -->
    <link href="https://vjs.zencdn.net/7.10.2/video-js.css" rel="stylesheet" />
    <script src="https://vjs.zencdn.net/7.10.2/video.min.js"></script>
    <script src="{% static 'video/js/controls.js' %}"></script>
{% endblock %}

{% block extracss %}
    <!-- customcss -->
    <link rel="stylesheet" type="text/css" href="{% static 'video/css/pose.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        {% if not video.is_estimated %}
            <div id="card" class="card">
                <div class="card-body">
                    <div class="row">
                        <button class="btn btn-primary col-12" id="start_button">
                            Pose Estimation
                        </button>
                    </div>

                    <div id="progress"></div>
                </div>
            </div>
        {% endif %}

        
        <div id="video-box" class="video-box">
            <video-js id="video" class="vjs-big-play-centered video overlay" controls playsinline>
                {% if video.is_estimated %}
                    <source src="{{ video.video_file }}" poster="{% static 'video/img/home.png' %}" type="video/mp4">
                {% else %}
                    <source src="{{ video.video_file.url }}" poster="{% static 'video/img/home.png' %}" type="video/mp4">
                {% endif %}
                <!--<source src="{% static video.video_file.url %}" poster="{% static 'video/img/home.png' %}" type="video/mp4">-->
            </video-js>
            
        </div>

        <div id ="check-box" class="not-visible">
            <button class="btn green lighten-1" onclick="location.href='{% url 'video:gallery' %}'">check</button>
        </div>

        
        
        <div id="del-btn" class="text-center">
            <!-- Modal Trigger -->
            <a class="red lighten-1 waves-effect waves-light btn modal-trigger" href="#modal1">Delete</a>
        </div>

        
        <!-- Modal Structure -->
        <div id="modal1" class="modal">
            <div class="modal-content">
                <p>Are you sure?</p>
            </div>
            <div class="modal-footer">
                <a class="btn red lighten-1 mx-2 del_btn modal-close" id="{{video.id}}">Delete</a>
            </div>
        </div>

        <script>
            // modal
            document.addEventListener('DOMContentLoaded', function() {
                var elems = document.querySelectorAll('.modal');
                var instances = M.Modal.init(elems, 'dismissible');
            });
        </script>

        <script>
            const Card = document.getElementById('card')
            const delBtn = document.getElementById('del-btn')
            const checkBox = document.getElementById('check-box')
            
            // Initial state of the progress bar display area
            const progresshtml = '<div id="progress"><div class="indeterminate"></div></div>';

            // Process when the start_button is pressed.
            $("#start_button").on("click", function (event) {
                delBtn.innerHTML = ""
                let timer_id = 0;
                let url = "{% url 'video:setup' %}"
                $("#start_button").attr({ "disabled": true })
                // Create the progress management instance
                $.get(url, {},
                    function (data) {
                        let pk = data
                        // Start getting the progress bar every 0.3 seconds.
                        timer_id = setInterval(function () { ShowProgressBar(pk) }, 300)
                        // Start time-consuming process
                        GetPose(pk)
                    }
                );
                // Get the progress bar
                function ShowProgressBar(progress_pk) {
                    $.get("{% url 'video:show_progress' %}", { progress_pk: progress_pk },
                        function (data) {
                            // console.log("Data Loaded: " + data);
                            $("#progress").replaceWith(data);
                            // Change process bar once the processing of the frames are completed
                            if (document.getElementById("complete")){
                                // Stop updating the progress bar
                                clearInterval(timer_id);
                                let complete = document.getElementById('complete')
                                complete.classList.add('indeterminate')
                            }
                        }
                    );
                }
                // Time-consuming process
                function GetPose(progress_pk) {
                    $.get("{% url 'video:pose_estimation' video.id %}", { progress_pk: progress_pk },
                        function (data) {
                            console.log("Data Loaded: " + data);
                            
                            // Display the process result 
                            $("#video").replaceWith(data)
                            //$("#start_button").attr({ "disabled": false })
                            //Card.innerHTML = ""
                            $("#card").fadeOut(0);
                            checkBox.classList.remove('not-visible')
                            
                        }
                    );
                }

            });
        </script>

        <script>
            let dlBtn = $('.del_btn');

            dlBtn.on('click', function(event){
                event.preventDefault();
                var videoId = $(this).attr('id');

                $.ajax({
                    type: 'GET',
                    url: '{% url "video:delete" %}',
                    data: {video_id: videoId},
                    dataType: 'json',
                    success: function(data){
                        if(data.video_id)
                        {
                            var videoId = data.video_id;
                            window.location.href = "{% url 'video:gallery' %}";
                        }
                    }
                }); 
            });
        </script>
    </div>
{% endblock %}

video/templates/video/progress_bar.html
{% load static %}

<div id="progress">
    {% if percent == "100%" %}
        <div class="progress">
            <div id="complete"></div>
        </div>
    {% else %}
        <div class="progress" style="height: 1%;">
            <div id="percent" class="progress-bar teal lighten-2" style="width:{{ percent }};">{{ percent }}</div>
        </div>
    {% endif %}
</div>

video/templates/video/result.html
{% load static %}

<video id="video" class="video" muted autoplay loop playsinline>
    <source id="video-url" src="{{ result_video.video_file }}" poster="" type="video/mp4">
    <!--<source id="video-url" src="{% static result_video.video_file.url %}" poster="{% static result_video.thumbnail.url %}" type="video/mp4">-->
</video>